#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to

# Changed by Hadi
## $OPENSHIFT_DIY_IP:8080
#nohup $OPENSHIFT_REPO_DIR/diy/testrubyserver.rb $OPENSHIFT_DIY_IP $OPENSHIFT_REPO_DIR/diy |& /usr/bin/logshifter -tag diy &
nohup JAVA_OPTS="-Dhttp.address=$OPENSHIFT_DIY_IP -Dhttp.port=$OPENSHIFT_DIY_PORT" $OPENSHIFT_REPO_DIR/diy/projects/planty-jira-web/target/universal/stage/bin/planty-jira-web |& /usr/bin/logshifter -tag diy &
